services:
  - type: web
    name: costing-engine
    runtime: python
    pythonVersion: 3.11.8
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
